my_tuple =()
print(my_tuple)
my_tuple = (1, 3 ,6)
print(my_tuple)
mt_tuple = (3, "Hello", 3.14)
print(my_tuple)
my_tuple =(2, [7,9,1], "James", (1,2,3))
print(my_tuple)
my_tuple = (2, [7,9,1], "James", (1,2,3))
print(my_tuple[0])
print(my_tuple[1][1])
print(my_tuple[1:3])
for letter in (my_tuple):
    print("Hello", letter)